server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password123
    key-store-type: PKCS12
    key-alias: mylocalcert

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# SSL 인증서 검증을 비활성화하기 위한 설정 추가
      healthcheck:
       enabled: true