server:
  port: 8030
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password123
    key-store-type: PKCS12
    key-alias: mylocalcert

spring:
  mybatis:
    type-aliases-package: com.example.jwtproject.model
    main:
      web-application-type: reactive
      cloud:
      gateway:
      httpclient:
       ssl:
          use-insecure-trust-manager: true

  sql:
    init:
      mode: never

  cloud:
      vault:
       uri: http://127.0.0.1:8200               # Vault 서버의 주소 (개발 모드일 경우 http 사용)
       token: ${VAULT_TOKEN}                    # Vault 접근 토큰 (환경 변수로 설정)
       kv:
        enabled: true
        backend: secret                        # Secret Engine의 기본 경로
        default-context: jwt-project           # 비밀이 저장될 경로

jwt:
  expiration-time: 5000                    # 10분 (밀리초 단위)
  refresh-expiration-time: 604800000          # 7일 (밀리초 단위)

vault:
  secret-path: secret/data/jwt-project        # secret 데이터 접근 경로 (key/value 버전 2에서 /data/ 추가)

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      instance:
        ecurePortEnabled: true
    instance:
      prefer-ip-address: true
    ssl:
      enabled: true
      validate-certs: false  # SSL 인증서 검증 비활성화

